/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import Empresa.ControladorEmpresa;
import espacios.Espacio;
import espacios.TipoEspacio;
import excepciones.EspacioDuplicadoException;
import excepciones.StoreBoxException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author UTN
 */
public class PanelEspacios extends javax.swing.JPanel {
    private ControladorEmpresa controlador;
    /**
     * Creates new form PanelEspacios
     */
    public PanelEspacios(ControladorEmpresa controlador) {
        initComponents();
        this.controlador = controlador;
        comboBuscarTipo.addItem(null);
        for(TipoEspacio t: TipoEspacio.values()){
            comboBuscarTipo.addItem(t);
        }
        refrescarTabla(controlador.listarEspacios());
        tablaEspacios.getSelectionModel().addListSelectionListener(evt -> cargarSeleccionEnFormulario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        lblNumero = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblEstadoTitulo = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        comboTipo = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        panelTabla = new javax.swing.JPanel();
        scrollTabla = new javax.swing.JScrollPane();
        tablaEspacios = new javax.swing.JTable();
        panelBusqueda = new javax.swing.JPanel();
        lblBuscarNumero = new javax.swing.JLabel();
        txtBuscarNumero = new javax.swing.JTextField();
        lblBuscarTipo = new javax.swing.JLabel();
        comboBuscarTipo = new javax.swing.JComboBox<>();
        lblBuscarDisponibilidad = new javax.swing.JLabel();
        comboBuscarDisponible = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        btnMostrarTodos = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        lblTitulo.setText("Administración de Espacios");

        panelDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNumero.setText("Número de espacio:");

        lblTipo.setText("Tipo:");

        lblPrecio.setText("Precio mensual:");

        lblEstadoTitulo.setText("Estado actual:");

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblEstado.setText("DISPONIBLE");

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEstadoTitulo)
                    .addComponent(lblPrecio)
                    .addComponent(lblTipo)
                    .addComponent(lblNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comboTipo, 0, 694, Short.MAX_VALUE)
                        .addComponent(txtNumero)
                        .addComponent(txtPrecio))
                    .addComponent(lblEstado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoTitulo)
                    .addComponent(lblEstado))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tablaEspacios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Tipo", "Tamaño (m2)", "Precio", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTabla.setViewportView(tablaEspacios);

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblBuscarNumero.setText("Número:");

        lblBuscarTipo.setText("Tipo:");

        lblBuscarDisponibilidad.setText("Disponibilidad:");

        comboBuscarDisponible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Disponibles", "Ocupados" }));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnMostrarTodos.setText("Mostrar todos");
        btnMostrarTodos.addActionListener(this::btnMostrarTodosActionPerformed);

        javax.swing.GroupLayout panelBusquedaLayout = new javax.swing.GroupLayout(panelBusqueda);
        panelBusqueda.setLayout(panelBusquedaLayout);
        panelBusquedaLayout.setHorizontalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscarNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBuscarTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBuscarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBuscarDisponibilidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBuscarDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrarTodos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBusquedaLayout.setVerticalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarNumero)
                    .addComponent(txtBuscarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscarTipo)
                    .addComponent(comboBuscarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscarDisponibilidad)
                    .addComponent(comboBuscarDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnMostrarTodos))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
        int numero = Integer.parseInt(txtNumero.getText().trim());
        TipoEspacio tipo = (TipoEspacio) comboTipo.getSelectedItem();
        Espacio espacio = new Espacio(numero, tipo);
        if(!txtPrecio.getText().trim().isBlank()){
            espacio.setPrecio(Double.parseDouble(txtPrecio.getText().trim()));
        }
            try {
                controlador.agregarEspacio(espacio);
            } catch (EspacioDuplicadoException ex) {
                System.getLogger(PanelEspacios.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        JOptionPane.showMessageDialog(this,"Espacio agregado correctamente");
        limpiarFormulario();
        refrescarTabla(controlador.listarEspacios());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"El número de espacio y numero de precio debe de ser numérico","Error", JOptionPane.ERROR_MESSAGE);
        }catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this,e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try{
        if(txtNumero.getText().trim().isBlank()){
            JOptionPane.showMessageDialog(this,"Selecione un espacio o esciba su número","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        int numero = Integer.parseInt(txtNumero.getText().trim());
        TipoEspacio tipo = (TipoEspacio) comboTipo.getSelectedItem();
        Double precio = txtPrecio.getText().trim().isBlank() ? null : Double.parseDouble(txtPrecio.getText().trim());
        try {
            controlador.actualizarEspacio(numero, tipo, precio);
        } catch (StoreBoxException ex) {
            System.getLogger(PanelEspacios.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        JOptionPane.showMessageDialog(this,"Espacio actualizado correctamente");
        limpiarFormulario();
        refrescarTabla(controlador.listarEspacios());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"El número de espacio y numero de precio debe de ser numérico","Error", JOptionPane.ERROR_MESSAGE);
        }catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this,e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try{
        if(txtNumero.getText().trim().isBlank()){
            JOptionPane.showMessageDialog(this,"Selecione un espacio de la tabla o escriba su numero","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        int numero = Integer.parseInt(txtNumero.getText().trim());
        int confirmacion = JOptionPane.showConfirmDialog
        (this, "Seguro que desea eliminar el" + numero + "?","Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION){
            return;
        }
            try {
                controlador.eliminarEspacio(numero);
            } catch (StoreBoxException ex) {
                System.getLogger(PanelEspacios.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        JOptionPane.showMessageDialog(this, "Espacio eliminado correctamente.");
        limpiarFormulario();
        refrescarTabla(controlador.listarEspacios());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"El número de espacio y numero de precio debe de ser numérico","Error", JOptionPane.ERROR_MESSAGE);
        }catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this,e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); 
        }     
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Integer numero = null;
        if(!txtBuscarNumero.getText().trim().isBlank()){
            try {
                numero = Integer.valueOf(txtBuscarNumero.getText().trim());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "El número debe ser numérico.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        TipoEspacio espacio = (TipoEspacio) comboBuscarTipo.getSelectedItem();
        Boolean disponible = switch ((String) comboBuscarDisponible.getSelectedItem()) {
            case "Disponibles" -> Boolean.TRUE;
            case "Ocupados" -> Boolean.FALSE;
            default -> null;
        };
        List<Espacio> resultado = controlador.buscarEspacio(numero, espacio, disponible, Double.NaN, Double.MIN_NORMAL);
        refrescarTabla(resultado);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosActionPerformed
        refrescarTabla(controlador.listarEspacios());
    }//GEN-LAST:event_btnMostrarTodosActionPerformed
    
    private void refrescarTabla(List<Espacio> espacio){
        DefaultTableModel modelo = (DefaultTableModel) tablaEspacios.getModel();
        modelo.setRowCount(0);
        for(Espacio e: espacio){
            modelo.addRow (new Object[]{
                e.getNumero(),e.getTipo(), e.getTamano(),e.getPrecio(),e.getEstado()});
            }
        }
    private void cargarSeleccionEnFormulario(){
        int fila = tablaEspacios.getSelectedRow();
        if (fila < 0){
            return;
        }
        DefaultTableModel modelo = (DefaultTableModel) tablaEspacios.getModel();
        txtNumero.setText(String.valueOf(modelo.getValueAt(fila, 0)));
        comboTipo.setSelectedItem(TipoEspacio.valueOf(String.valueOf(modelo.getValueAt(fila, 1))));
        txtPrecio.setText(String.valueOf(modelo.getValueAt(fila,3)));
        lblEstado.setText(String.valueOf(modelo.getValueAt(fila,4)));
        txtNumero.setEditable(false);
        
    }
    private void limpiarFormulario(){
        txtNumero.setText("");
        comboTipo.setSelectedIndex(0);
        txtPrecio.setText("");
        lblEstado.setText("Disponible");
        txtNumero.setEditable(true);
        tablaEspacios.clearSelection();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JComboBox<String> comboBuscarDisponible;
    private javax.swing.JComboBox<TipoEspacio> comboBuscarTipo;
    private javax.swing.JComboBox<TipoEspacio> comboTipo;
    private javax.swing.JLabel lblBuscarDisponibilidad;
    private javax.swing.JLabel lblBuscarNumero;
    private javax.swing.JLabel lblBuscarTipo;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoTitulo;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JTable tablaEspacios;
    private javax.swing.JTextField txtBuscarNumero;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}

